spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  #    datasource:
  #      url: jdbc:h2:mem:testdb
  #      username: sa
  #      password:
  #      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace
  servlet:
    multipart:
      file-size-threshold: 1MB
      location: /Users/user/data
      max-file-size: 100MB
      max-request-size: 100MB